In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

import matplotlib
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
df=pd.read_csv("Case study data set.csv")

In [3]:
df.head()

,Season,Supplier,Original Order-No.,Order-No.,Order Date,PO Category,Article,Style,Color Code,Color Description,...,Warehouse,Destination/Country,Requested XF date,Fty. 1st Conf. Ready Date,Current Ex-Fty. Date,Delay reason,Qty. ord.,Qty. Cfmd.,Current Price/Piece,Mode of Transport
0,SS24,Eagle Textile,PO01OM003594,PO01OM003594,13.07.23,Bulk,344.00816,344,816.0,Black | Shadow,...,LUX-KN-STK,Luxembourg,22.09.23,22.09.23,22.09.23,NaN,600.0,600,3.28,Truck
1,SS24,Eagle Textile,PO01OM003594,PO01OM003594,13.07.23,Bulk,354.00825,354,825.0,Black | Shadow,...,LUX-KN-STK,Luxembourg,22.09.23,22.09.23,22.09.23,NaN,700.0,700,3.6,Truck
2,SS24,Eagle Textile,PO01OM003594,PO01OM003594,13.07.23,Bulk,364.00836,364,836.0,Black | Shadow,...,LUX-KN-STK,Luxembourg,22.09.23,22.09.23,22.09.23,NaN,1050.0,1050,4.28,Truck
3,SS24,Eagle Textile,PO01OM003594,PO01OM003594,13.07.23,Bulk,354.00826,354,826.0,White | Ivory,...,LUX-KN-STK,Luxembourg,22.09.23,22.09.23,22.09.23,NaN,700.0,700,3.6,Truck
4,SS24,Eagle Textile,PO01OM003594,PO01OM003594,13.07.23,Bulk,345.00822,345,822.0,White | Ivory,...,LUX-KN-STK,Luxembourg,22.09.23,22.09.23,22.09.23,NaN,600.0,600,3.28,Truck

In [4]:
df.columns=df.columns.str.lower().str.replace(' ','_')
df.columns=df.columns.str.lower().str.replace('-','_')
df.columns=df.columns.str.lower().str.replace('.','')

C:\Users\sondu\AppData\Local\Temp\ipykernel_4624\140332619.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df.columns=df.columns.str.lower().str.replace('.','')

In [5]:
df.head()

,season,supplier,original_order_no,order_no,order_date,po_category,article,style,color_code,color_description,...,warehouse,destination/country,requested_xf_date,fty_1st_conf_ready_date,current_ex_fty_date,delay_reason,qty_ord,qty_cfmd,current_price/piece,mode_of_transport
0,SS24,Eagle Textile,PO01OM003594,PO01OM003594,13.07.23,Bulk,344.00816,344,816.0,Black | Shadow,...,LUX-KN-STK,Luxembourg,22.09.23,22.09.23,22.09.23,NaN,600.0,600,3.28,Truck
1,SS24,Eagle Textile,PO01OM003594,PO01OM003594,13.07.23,Bulk,354.00825,354,825.0,Black | Shadow,...,LUX-KN-STK,Luxembourg,22.09.23,22.09.23,22.09.23,NaN,700.0,700,3.6,Truck
2,SS24,Eagle Textile,PO01OM003594,PO01OM003594,13.07.23,Bulk,364.00836,364,836.0,Black | Shadow,...,LUX-KN-STK,Luxembourg,22.09.23,22.09.23,22.09.23,NaN,1050.0,1050,4.28,Truck
3,SS24,Eagle Textile,PO01OM003594,PO01OM003594,13.07.23,Bulk,354.00826,354,826.0,White | Ivory,...,LUX-KN-STK,Luxembourg,22.09.23,22.09.23,22.09.23,NaN,700.0,700,3.6,Truck
4,SS24,Eagle Textile,PO01OM003594,PO01OM003594,13.07.23,Bulk,345.00822,345,822.0,White | Ivory,...,LUX-KN-STK,Luxembourg,22.09.23,22.09.23,22.09.23,NaN,600.0,600,3.28,Truck

In [6]:
print(df.dtypes)

season                      object
supplier                    object
original_order_no           object
order_no                    object
order_date                  object
po_category                 object
article                     object
style                       object
color_code                 float64
color_description           object
model_name                  object
warehouse                   object
destination/country         object
requested_xf_date           object
fty_1st_conf_ready_date     object
current_ex_fty_date         object
delay_reason                object
qty_ord                    float64
qty_cfmd                     int64
current_price/piece         object
mode_of_transport           object
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6315 entries, 0 to 6314
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   season                   6314 non-null   object
 1   supplier                 6314 non-null   object
 2   original_order_no        6314 non-null   object
 3   order_no                 6314 non-null   object
 4   order_date               6314 non-null   object
 5   po_category              6314 non-null   object
 6   article                  6314 non-null   object
 7   style                    6314 non-null   object
 8   color_code               5077 non-null   float64
 9   color_description        6314 non-null   object
 10  model_name               6314 non-null   object
 11  warehouse                6314 non-null   object
 12  destination/country      6314 non-null   object
 13  requested_xf_date        6314 non-null   object
 14  fty_1st_conf_ready_date  6314 non-null   object
 15  current_ex_fty_date      6314 non-null   object
 16  delay_reason             3677 non-null   object
 17  qty_ord                  6314 non-null   float64
 18  qty_cfmd                 6315 non-null   int64
 19  current_price/piece      6315 non-null   object
 20  mode_of_transport        6314 non-null   object
dtypes: float64(2), int64(1), object(18)
memory usage: 1.0+ MB

In [8]:
df.describe()

         color_code      qty_ord      qty_cfmd
count   5077.000000  6314.000000  6.315000e+03
mean    1019.788064   270.364903  5.243834e+02
std      592.542033   448.194911  2.192429e+04
min       57.000000     1.000000  1.000000e+00
25%      831.000000    50.000000  4.600000e+01
50%      881.000000   120.000000  1.000000e+02
75%     1191.000000   300.000000  2.600000e+02
max    10211.000000  6900.000000  1.742171e+06

In [9]:
#check for missing data
for col in df.columns:
    pct_missing=np.mean(df[col].isnull())
    print('{} - {}%'.format(col,pct_missing))

season - 0.00015835312747426763%
supplier - 0.00015835312747426763%
original_order_no - 0.00015835312747426763%
order_no - 0.00015835312747426763%
order_date - 0.00015835312747426763%
po_category - 0.00015835312747426763%
article - 0.00015835312747426763%
style - 0.00015835312747426763%
color_code - 0.19604117181314332%
color_description - 0.00015835312747426763%
model_name - 0.00015835312747426763%
warehouse - 0.00015835312747426763%
destination/country - 0.00015835312747426763%
requested_xf_date - 0.00015835312747426763%
fty_1st_conf_ready_date - 0.00015835312747426763%
current_ex_fty_date - 0.00015835312747426763%
delay_reason - 0.41773555027711795%
qty_ord - 0.00015835312747426763%
qty_cfmd - 0.0%
current_price/piece - 0.0%
mode_of_transport - 0.00015835312747426763%

In [10]:
for col in df.columns:
    print(col)
    print(df[col].unique()[:5])
    print(df[col].nunique())
    print()

season
['SS24' 'FW22' 'SS23' 'FW23' 'SS22']
5

supplier
['Eagle Textile' 'OVERCLOTHES S.p.A.' 'STONETEX MANUFACTURING SA'
 'RIM Tekstil A.S.' 'Gunther Bohr GMBH']
5

original_order_no
['PO01OM003594' 'PO010035681' 'PO010035684' 'PO010035682' 'PO010035677']
922

order_no
['PO01OM003594' 'PO010035681' 'PO010035684' 'PO010035682' 'PO010035677']
961

order_date
['13.07.23' '25.02.22' '24.02.22' '29.07.22' '25.08.22']
76

po_category
['Bulk' 'Special Ed' 'Media' nan]
3

article
['344.00816' '354.00825' '364.00836' '354.00826' '345.00822']
354

style
['344' '354' '364' '345' '355']
171

color_code
[816. 825. 836. 826. 822.]
239

color_description
['Black | Shadow' 'White | Ivory' 'Black' 'Comet | Flame'
 'Zest | Stratosphere']
114

model_name
['Performance Low Sock' 'Performance Mid Sock' 'Performance High Sock'
 'Logo Sock 3-Pack' 'All-Day Sock']
64

warehouse
['LUX-KN-STK' 'IC JP TOY' 'IC CN SHA' 'IC AU MEL' 'IC HK HKG']
16

destination/country
['Luxembourg' 'Japan' 'China' 'Australia' 'Hong Kong']
10

requested_xf_date
['22.09.23' '20.06.22' '17.04.22' '27.06.22' '03.10.22']
66

fty_1st_conf_ready_date
['22.09.23' '20.06.22' '15.05.22' '27.06.22' '03.10.22']
95

current_ex_fty_date
['22.09.23' '05.08.22' '09.09.22' '03.04.23' '15.02.23']
132

delay_reason
[nan 'Trims delay' 'Fabric Delay' 'Capacity constraint']
3

qty_ord
[ 600.  700. 1050. 1000.  100.]
580

qty_cfmd
[ 600  700 1050 1000  100]
632

current_price/piece
['3.28' '3.6' '4.28' '5.08' '4.26']
156

mode_of_transport
['Truck' 'Sea' 'Air' nan]
3

In [11]:
df['delay'] = df['delay_reason'].notna()

In [12]:
df.head()

,season,supplier,original_order_no,order_no,order_date,po_category,article,style,color_code,color_description,...,destination/country,requested_xf_date,fty_1st_conf_ready_date,current_ex_fty_date,delay_reason,qty_ord,qty_cfmd,current_price/piece,mode_of_transport,delay
0,SS24,Eagle Textile,PO01OM003594,PO01OM003594,13.07.23,Bulk,344.00816,344,816.0,Black | Shadow,...,Luxembourg,22.09.23,22.09.23,22.09.23,NaN,600.0,600,3.28,Truck,False
1,SS24,Eagle Textile,PO01OM003594,PO01OM003594,13.07.23,Bulk,354.00825,354,825.0,Black | Shadow,...,Luxembourg,22.09.23,22.09.23,22.09.23,NaN,700.0,700,3.6,Truck,False
2,SS24,Eagle Textile,PO01OM003594,PO01OM003594,13.07.23,Bulk,364.00836,364,836.0,Black | Shadow,...,Luxembourg,22.09.23,22.09.23,22.09.23,NaN,1050.0,1050,4.28,Truck,False
3,SS24,Eagle Textile,PO01OM003594,PO01OM003594,13.07.23,Bulk,354.00826,354,826.0,White | Ivory,...,Luxembourg,22.09.23,22.09.23,22.09.23,NaN,700.0,700,3.6,Truck,False
4,SS24,Eagle Textile,PO01OM003594,PO01OM003594,13.07.23,Bulk,345.00822,345,822.0,White | Ivory,...,Luxembourg,22.09.23,22.09.23,22.09.23,NaN,600.0,600,3.28,Truck,False

In [13]:
df.delay==(df.delay=='yes').astype(int)

0       True
1       True
2       True
3       True
4       True
        ...
6310    True
6311    True
6312    True
6313    True
6314    True
Name: delay, Length: 6315, dtype: bool

In [14]:
df.color_code

0         816.0
1         825.0
2         836.0
3         826.0
4         822.0
         ...
6310    10211.0
6311      219.0
6312      222.0
6313      218.0
6314        NaN
Name: color_code, Length: 6315, dtype: float64

In [15]:
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [16]:
for col in df.columns:
    df[col] = df[col].fillna(0)

In [17]:
df.isnull().sum()

season                     0
supplier                   0
original_order_no          0
order_no                   0
order_date                 0
po_category                0
article                    0
style                      0
color_code                 0
color_description          0
model_name                 0
warehouse                  0
destination/country        0
requested_xf_date          0
fty_1st_conf_ready_date    0
current_ex_fty_date        0
delay_reason               0
qty_ord                    0
qty_cfmd                   0
current_price/piece        0
mode_of_transport          0
delay                      0
dtype: int64

In [18]:
for col in df.columns:
    print(col)
    print(df[col].unique()[:5])
    print(df[col].nunique())
    print()

season
[0.]
1

supplier
[0.]
1

original_order_no
[0.]
1

order_no
[0.]
1

order_date
[0.]
1

po_category
[0.]
1

article
[344.00816 354.00825 364.00836 354.00826 345.00822]
240

style
[344. 354. 364. 345. 355.]
57

color_code
[816. 825. 836. 826. 822.]
240

color_description
[0.]
1

model_name
[0.]
1

warehouse
[0.]
1

destination/country
[0.]
1

requested_xf_date
[0.]
1

fty_1st_conf_ready_date
[0.]
1

current_ex_fty_date
[0.]
1

delay_reason
[0.]
1

qty_ord
[ 600.  700. 1050. 1000.  100.]
581

qty_cfmd
[ 600  700 1050 1000  100]
632

current_price/piece
[3.28 3.6  4.28 5.08 4.26]
155

mode_of_transport
[0.]
1

delay
[False  True]
2

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [21]:
len(df_train), len(df_val), len(df_test)

(3789, 1263, 1263)

In [22]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [23]:
y_train = df_train.delay.values
y_val = df_val.delay.values
y_test = df_test.delay.values

del df_train['delay']
del df_val['delay']
del df_test['delay']

In [24]:
df_full_train = df_full_train.reset_index(drop=True)

In [25]:
df_full_train.delay.value_counts(normalize=True)

True     0.581354
False    0.418646
Name: delay, dtype: float64

In [26]:
global_delay_rate=df_full_train.delay.mean()
round(global_delay_rate,2)

0.58

In [27]:
df_full_train.dtypes

season                     float64
supplier                   float64
original_order_no          float64
order_no                   float64
order_date                 float64
po_category                float64
article                    float64
style                      float64
color_code                 float64
color_description          float64
model_name                 float64
warehouse                  float64
destination/country        float64
requested_xf_date          float64
fty_1st_conf_ready_date    float64
current_ex_fty_date        float64
delay_reason               float64
qty_ord                    float64
qty_cfmd                     int64
current_price/piece        float64
mode_of_transport          float64
delay                         bool
dtype: object

In [28]:
categories=['season','supplier','po_category','destination/country','qty_ord','warehouse','mode_of_transport']

In [29]:
from sklearn.feature_extraction import DictVectorizer

In [30]:
dv = DictVectorizer(sparse=False)

train_dict = df_train[categories].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categories].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
model = LogisticRegression(solver='lbfgs')
model.fit(X_train, y_train)

LogisticRegression()